package relationshipby.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DomainAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDomainAllPropertiesEquals(Domain expected, Domain actual) {
        assertDomainAutoGeneratedPropertiesEquals(expected, actual);
        assertDomainAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDomainAllUpdatablePropertiesEquals(Domain expected, Domain actual) {
        assertDomainUpdatableFieldsEquals(expected, actual);
        assertDomainUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDomainAutoGeneratedPropertiesEquals(Domain expected, Domain actual) {
        assertThat(actual)
            .as("Verify Domain auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDomainUpdatableFieldsEquals(Domain expected, Domain actual) {
        assertThat(actual)
            .as("Verify Domain relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDomainUpdatableRelationshipsEquals(Domain expected, Domain actual) {
        // empty method
    }
}
